### ISSUE TITLE
`deriving.K0.foldRight` is broken

### ISSUE THREAD

**Issue by xuwei-k** [typelevel/shapeless-3#12]
### `build.sbt`

```scala
libraryDependencies += "org.typelevel" %% "shapeless3-deriving" % "3.0.1"

scalaVersion := "3.0.0"
```

### `Main.scala`

```scala
import shapeless3.deriving.K0

trait TypeClass[A] { def method(a: A): Int }

case class Pair[A](a1: A, a2: A)

object Main {

  given TypeClass[Int] = (a: Int) => a

  def main(args: Array[String]): Unit = {
    val x = summon[K0.ProductInstances[TypeClass, Pair[Int]]]
    val p = Pair(1, 2)

    println(
      x.foldLeft [String](p)("a")([t] => (acc: String, f: TypeClass[t], t: t) => acc + " " + f.method(t))
    )

    println(
      x.foldRight[String](p)("a")([t] => (acc: String, f: TypeClass[t], t: t) => acc + " " + f.method(t))
    )
  }
}
```

### output

```
[info] running Main 
a 1 2
[error] (run-main-2) java.lang.ClassCastException: Main$$$Lambda$7840/1897796610 cannot be cast to java.lang.String
[error] java.lang.ClassCastException: Main$$$Lambda$7840/1897796610 cannot be cast to java.lang.String
[error] 	at Main$$anon$2.apply(Main.scala:20)
[error] 	at shapeless3.deriving.internals.ErasedProductInstancesN.loop$2(erased.scala:214)
[error] 	at shapeless3.deriving.internals.ErasedProductInstancesN.erasedFoldRight(erased.scala:220)
[error] 	at Main$.main(Main.scala:20)
[error] 	at Main.main(Main.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] stack trace is suppressed; run last Compile / bgRun for the full output
[error] Nonzero exit code: 1
[error] (Compile / run) Nonzero exit code: 1
```

https://github.com/typelevel/shapeless-3/blob/3c2696b7780e1544ec672f2aca44f459c01f02f7/modules/deriving/src/main/scala/shapeless3/deriving/kinds.scala#L105-L106

**Comment by milessabin** [comment]
Good spot .. thanks!
